export const START_TRIVIA = 'START_TRIVIA';

export const TIMEOUT_ACTION = 'TIMEOUT_ACTION';

export const CLEAR_STATE = 'CLEAR_STATE';

export const INCREASE_SCORE = 'INCREASE_SCORE';

export const SAVE_USER_DATA = 'SAVE_USER_DATA';

export const CREATE_OPTIONS = 'CREATE_OPTIONS';
